/**
 * Static list of countries with ISO codes and dial codes (ITU-T E.164).
 * Flag emojis are generated from ISO codes using Unicode Regional Indicator Symbols.
 */

export interface Country {
  code: string;   // ISO 3166-1 alpha-2
  name: string;   // Portuguese name
  dialCode: string;
}

export function getFlagEmoji(countryCode: string): string {
  return countryCode
    .toUpperCase()
    .replace(/./g, (char) => String.fromCodePoint(127397 + char.charCodeAt(0)));
}

/** Parse an existing full phone string into { dialCode, phone } */
export function splitPhone(full: string): { dialCode: string; phone: string } {
  const digits = full.replace(/\D/g, "");
  // Try to match known dial codes (longest first up to 4 digits)
  for (let len = 4; len >= 1; len--) {
    const prefix = digits.slice(0, len);
    const match = COUNTRIES.find((c) => c.dialCode === `+${prefix}`);
    if (match) {
      return { dialCode: match.dialCode, phone: digits.slice(len) };
    }
  }
  // Default: assume +55 Brazil
  if (digits.startsWith("55") && digits.length > 10) {
    return { dialCode: "+55", phone: digits.slice(2) };
  }
  return { dialCode: "+55", phone: digits };
}

// Brazil first, then alphabetical
export const COUNTRIES: Country[] = [
  { code: "BR", name: "Brasil", dialCode: "+55" },
  { code: "PT", name: "Portugal", dialCode: "+351" },
  { code: "US", name: "Estados Unidos", dialCode: "+1" },
  { code: "AF", name: "Afeganistão", dialCode: "+93" },
  { code: "ZA", name: "África do Sul", dialCode: "+27" },
  { code: "AL", name: "Albânia", dialCode: "+355" },
  { code: "DE", name: "Alemanha", dialCode: "+49" },
  { code: "AD", name: "Andorra", dialCode: "+376" },
  { code: "AO", name: "Angola", dialCode: "+244" },
  { code: "AG", name: "Antígua e Barbuda", dialCode: "+1268" },
  { code: "SA", name: "Arábia Saudita", dialCode: "+966" },
  { code: "DZ", name: "Argélia", dialCode: "+213" },
  { code: "AR", name: "Argentina", dialCode: "+54" },
  { code: "AM", name: "Armênia", dialCode: "+374" },
  { code: "AU", name: "Austrália", dialCode: "+61" },
  { code: "AT", name: "Áustria", dialCode: "+43" },
  { code: "AZ", name: "Azerbaijão", dialCode: "+994" },
  { code: "BS", name: "Bahamas", dialCode: "+1242" },
  { code: "BH", name: "Bahrein", dialCode: "+973" },
  { code: "BD", name: "Bangladesh", dialCode: "+880" },
  { code: "BB", name: "Barbados", dialCode: "+1246" },
  { code: "BY", name: "Bielorrússia", dialCode: "+375" },
  { code: "BE", name: "Bélgica", dialCode: "+32" },
  { code: "BZ", name: "Belize", dialCode: "+501" },
  { code: "BJ", name: "Benin", dialCode: "+229" },
  { code: "BT", name: "Butão", dialCode: "+975" },
  { code: "BO", name: "Bolívia", dialCode: "+591" },
  { code: "BA", name: "Bósnia e Herzegovina", dialCode: "+387" },
  { code: "BW", name: "Botsuana", dialCode: "+267" },
  { code: "BN", name: "Brunei", dialCode: "+673" },
  { code: "BG", name: "Bulgária", dialCode: "+359" },
  { code: "BF", name: "Burkina Faso", dialCode: "+226" },
  { code: "BI", name: "Burundi", dialCode: "+257" },
  { code: "CV", name: "Cabo Verde", dialCode: "+238" },
  { code: "KH", name: "Camboja", dialCode: "+855" },
  { code: "CM", name: "Camarões", dialCode: "+237" },
  { code: "CA", name: "Canadá", dialCode: "+1" },
  { code: "QA", name: "Catar", dialCode: "+974" },
  { code: "KZ", name: "Cazaquistão", dialCode: "+7" },
  { code: "TD", name: "Chade", dialCode: "+235" },
  { code: "CL", name: "Chile", dialCode: "+56" },
  { code: "CN", name: "China", dialCode: "+86" },
  { code: "CY", name: "Chipre", dialCode: "+357" },
  { code: "CO", name: "Colômbia", dialCode: "+57" },
  { code: "KM", name: "Comores", dialCode: "+269" },
  { code: "CG", name: "Congo", dialCode: "+242" },
  { code: "CD", name: "Congo (RDC)", dialCode: "+243" },
  { code: "KR", name: "Coreia do Sul", dialCode: "+82" },
  { code: "KP", name: "Coreia do Norte", dialCode: "+850" },
  { code: "CI", name: "Costa do Marfim", dialCode: "+225" },
  { code: "CR", name: "Costa Rica", dialCode: "+506" },
  { code: "HR", name: "Croácia", dialCode: "+385" },
  { code: "CU", name: "Cuba", dialCode: "+53" },
  { code: "DK", name: "Dinamarca", dialCode: "+45" },
  { code: "DJ", name: "Djibuti", dialCode: "+253" },
  { code: "DM", name: "Dominica", dialCode: "+1767" },
  { code: "EG", name: "Egito", dialCode: "+20" },
  { code: "SV", name: "El Salvador", dialCode: "+503" },
  { code: "AE", name: "Emirados Árabes Unidos", dialCode: "+971" },
  { code: "EC", name: "Equador", dialCode: "+593" },
  { code: "ER", name: "Eritreia", dialCode: "+291" },
  { code: "SK", name: "Eslováquia", dialCode: "+421" },
  { code: "SI", name: "Eslovênia", dialCode: "+386" },
  { code: "ES", name: "Espanha", dialCode: "+34" },
  { code: "EE", name: "Estônia", dialCode: "+372" },
  { code: "SZ", name: "Esuatíni", dialCode: "+268" },
  { code: "ET", name: "Etiópia", dialCode: "+251" },
  { code: "FJ", name: "Fiji", dialCode: "+679" },
  { code: "PH", name: "Filipinas", dialCode: "+63" },
  { code: "FI", name: "Finlândia", dialCode: "+358" },
  { code: "FR", name: "França", dialCode: "+33" },
  { code: "GA", name: "Gabão", dialCode: "+241" },
  { code: "GM", name: "Gâmbia", dialCode: "+220" },
  { code: "GH", name: "Gana", dialCode: "+233" },
  { code: "GE", name: "Geórgia", dialCode: "+995" },
  { code: "GR", name: "Grécia", dialCode: "+30" },
  { code: "GD", name: "Granada", dialCode: "+1473" },
  { code: "GT", name: "Guatemala", dialCode: "+502" },
  { code: "GY", name: "Guiana", dialCode: "+592" },
  { code: "GN", name: "Guiné", dialCode: "+224" },
  { code: "GQ", name: "Guiné Equatorial", dialCode: "+240" },
  { code: "GW", name: "Guiné-Bissau", dialCode: "+245" },
  { code: "HT", name: "Haiti", dialCode: "+509" },
  { code: "HN", name: "Honduras", dialCode: "+504" },
  { code: "HU", name: "Hungria", dialCode: "+36" },
  { code: "YE", name: "Iêmen", dialCode: "+967" },
  { code: "IN", name: "Índia", dialCode: "+91" },
  { code: "ID", name: "Indonésia", dialCode: "+62" },
  { code: "IQ", name: "Iraque", dialCode: "+964" },
  { code: "IR", name: "Irã", dialCode: "+98" },
  { code: "IE", name: "Irlanda", dialCode: "+353" },
  { code: "IS", name: "Islândia", dialCode: "+354" },
  { code: "IL", name: "Israel", dialCode: "+972" },
  { code: "IT", name: "Itália", dialCode: "+39" },
  { code: "JM", name: "Jamaica", dialCode: "+1876" },
  { code: "JP", name: "Japão", dialCode: "+81" },
  { code: "JO", name: "Jordânia", dialCode: "+962" },
  { code: "KW", name: "Kuwait", dialCode: "+965" },
  { code: "KG", name: "Quirguistão", dialCode: "+996" },
  { code: "LA", name: "Laos", dialCode: "+856" },
  { code: "LS", name: "Lesoto", dialCode: "+266" },
  { code: "LV", name: "Letônia", dialCode: "+371" },
  { code: "LB", name: "Líbano", dialCode: "+961" },
  { code: "LR", name: "Libéria", dialCode: "+231" },
  { code: "LY", name: "Líbia", dialCode: "+218" },
  { code: "LI", name: "Liechtenstein", dialCode: "+423" },
  { code: "LT", name: "Lituânia", dialCode: "+370" },
  { code: "LU", name: "Luxemburgo", dialCode: "+352" },
  { code: "MK", name: "Macedônia do Norte", dialCode: "+389" },
  { code: "MG", name: "Madagáscar", dialCode: "+261" },
  { code: "MY", name: "Malásia", dialCode: "+60" },
  { code: "MW", name: "Malawi", dialCode: "+265" },
  { code: "MV", name: "Maldivas", dialCode: "+960" },
  { code: "ML", name: "Mali", dialCode: "+223" },
  { code: "MT", name: "Malta", dialCode: "+356" },
  { code: "MA", name: "Marrocos", dialCode: "+212" },
  { code: "MU", name: "Maurício", dialCode: "+230" },
  { code: "MR", name: "Mauritânia", dialCode: "+222" },
  { code: "MX", name: "México", dialCode: "+52" },
  { code: "MM", name: "Mianmar", dialCode: "+95" },
  { code: "FM", name: "Micronésia", dialCode: "+691" },
  { code: "MZ", name: "Moçambique", dialCode: "+258" },
  { code: "MD", name: "Moldávia", dialCode: "+373" },
  { code: "MC", name: "Mônaco", dialCode: "+377" },
  { code: "MN", name: "Mongólia", dialCode: "+976" },
  { code: "ME", name: "Montenegro", dialCode: "+382" },
  { code: "NA", name: "Namíbia", dialCode: "+264" },
  { code: "NR", name: "Nauru", dialCode: "+674" },
  { code: "NP", name: "Nepal", dialCode: "+977" },
  { code: "NI", name: "Nicarágua", dialCode: "+505" },
  { code: "NE", name: "Níger", dialCode: "+227" },
  { code: "NG", name: "Nigéria", dialCode: "+234" },
  { code: "NO", name: "Noruega", dialCode: "+47" },
  { code: "NZ", name: "Nova Zelândia", dialCode: "+64" },
  { code: "OM", name: "Omã", dialCode: "+968" },
  { code: "NL", name: "Países Baixos", dialCode: "+31" },
  { code: "PW", name: "Palau", dialCode: "+680" },
  { code: "PA", name: "Panamá", dialCode: "+507" },
  { code: "PG", name: "Papua-Nova Guiné", dialCode: "+675" },
  { code: "PK", name: "Paquistão", dialCode: "+92" },
  { code: "PY", name: "Paraguai", dialCode: "+595" },
  { code: "PE", name: "Peru", dialCode: "+51" },
  { code: "PL", name: "Polônia", dialCode: "+48" },
  { code: "DO", name: "República Dominicana", dialCode: "+1809" },
  { code: "CF", name: "República Centro-Africana", dialCode: "+236" },
  { code: "CZ", name: "República Tcheca", dialCode: "+420" },
  { code: "RO", name: "Romênia", dialCode: "+40" },
  { code: "RW", name: "Ruanda", dialCode: "+250" },
  { code: "RU", name: "Rússia", dialCode: "+7" },
  { code: "KN", name: "São Cristóvão e Névis", dialCode: "+1869" },
  { code: "LC", name: "Santa Lúcia", dialCode: "+1758" },
  { code: "VC", name: "São Vicente e Granadinas", dialCode: "+1784" },
  { code: "WS", name: "Samoa", dialCode: "+685" },
  { code: "SM", name: "San Marino", dialCode: "+378" },
  { code: "ST", name: "São Tomé e Príncipe", dialCode: "+239" },
  { code: "SN", name: "Senegal", dialCode: "+221" },
  { code: "RS", name: "Sérvia", dialCode: "+381" },
  { code: "SC", name: "Seychelles", dialCode: "+248" },
  { code: "SL", name: "Serra Leoa", dialCode: "+232" },
  { code: "SG", name: "Singapura", dialCode: "+65" },
  { code: "SY", name: "Síria", dialCode: "+963" },
  { code: "SO", name: "Somália", dialCode: "+252" },
  { code: "LK", name: "Sri Lanka", dialCode: "+94" },
  { code: "SD", name: "Sudão", dialCode: "+249" },
  { code: "SS", name: "Sudão do Sul", dialCode: "+211" },
  { code: "SE", name: "Suécia", dialCode: "+46" },
  { code: "CH", name: "Suíça", dialCode: "+41" },
  { code: "SR", name: "Suriname", dialCode: "+597" },
  { code: "TH", name: "Tailândia", dialCode: "+66" },
  { code: "TW", name: "Taiwan", dialCode: "+886" },
  { code: "TJ", name: "Tajiquistão", dialCode: "+992" },
  { code: "TZ", name: "Tanzânia", dialCode: "+255" },
  { code: "TL", name: "Timor-Leste", dialCode: "+670" },
  { code: "TG", name: "Togo", dialCode: "+228" },
  { code: "TO", name: "Tonga", dialCode: "+676" },
  { code: "TT", name: "Trinidad e Tobago", dialCode: "+1868" },
  { code: "TN", name: "Tunísia", dialCode: "+216" },
  { code: "TM", name: "Turcomenistão", dialCode: "+993" },
  { code: "TR", name: "Turquia", dialCode: "+90" },
  { code: "TV", name: "Tuvalu", dialCode: "+688" },
  { code: "UA", name: "Ucrânia", dialCode: "+380" },
  { code: "UG", name: "Uganda", dialCode: "+256" },
  { code: "UY", name: "Uruguai", dialCode: "+598" },
  { code: "UZ", name: "Uzbequistão", dialCode: "+998" },
  { code: "VU", name: "Vanuatu", dialCode: "+678" },
  { code: "VA", name: "Vaticano", dialCode: "+379" },
  { code: "VE", name: "Venezuela", dialCode: "+58" },
  { code: "VN", name: "Vietnã", dialCode: "+84" },
  { code: "ZM", name: "Zâmbia", dialCode: "+260" },
  { code: "ZW", name: "Zimbábue", dialCode: "+263" },
];
