export interface MetaLanguage {
  code: string;
  name: string;
}

export const META_LANGUAGES: MetaLanguage[] = [
  { code: "af", name: "Africâner" },
  { code: "sq", name: "Albanês" },
  { code: "ar", name: "Árabe" },
  { code: "az", name: "Azerbaijano" },
  { code: "bn", name: "Bengali" },
  { code: "bg", name: "Búlgaro" },
  { code: "ca", name: "Catalão" },
  { code: "zh_CN", name: "Chinês (Simplificado)" },
  { code: "zh_HK", name: "Chinês (Hong Kong)" },
  { code: "zh_TW", name: "Chinês (Tradicional)" },
  { code: "hr", name: "Croata" },
  { code: "cs", name: "Tcheco" },
  { code: "da", name: "Dinamarquês" },
  { code: "nl", name: "Holandês" },
  { code: "en", name: "Inglês" },
  { code: "en_GB", name: "Inglês (UK)" },
  { code: "en_US", name: "Inglês (US)" },
  { code: "et", name: "Estoniano" },
  { code: "fil", name: "Filipino" },
  { code: "fi", name: "Finlandês" },
  { code: "fr", name: "Francês" },
  { code: "ka", name: "Georgiano" },
  { code: "de", name: "Alemão" },
  { code: "el", name: "Grego" },
  { code: "gu", name: "Gujarati" },
  { code: "ha", name: "Hauçá" },
  { code: "he", name: "Hebraico" },
  { code: "hi", name: "Hindi" },
  { code: "hu", name: "Húngaro" },
  { code: "id", name: "Indonésio" },
  { code: "ga", name: "Irlandês" },
  { code: "it", name: "Italiano" },
  { code: "ja", name: "Japonês" },
  { code: "kn", name: "Canarês" },
  { code: "kk", name: "Cazaque" },
  { code: "rw_RW", name: "Kinyarwanda" },
  { code: "ko", name: "Coreano" },
  { code: "ky_KG", name: "Quirguiz" },
  { code: "lo", name: "Laosiano" },
  { code: "lv", name: "Letão" },
  { code: "lt", name: "Lituano" },
  { code: "mk", name: "Macedônio" },
  { code: "ms", name: "Malaio" },
  { code: "ml", name: "Malaiala" },
  { code: "mr", name: "Marata" },
  { code: "nb", name: "Norueguês (Bokmål)" },
  { code: "fa", name: "Persa" },
  { code: "pl", name: "Polonês" },
  { code: "pt_BR", name: "Português (BR)" },
  { code: "pt_PT", name: "Português (PT)" },
  { code: "pa", name: "Punjabi" },
  { code: "ro", name: "Romeno" },
  { code: "ru", name: "Russo" },
  { code: "sr", name: "Sérvio" },
  { code: "sk", name: "Eslovaco" },
  { code: "sl", name: "Esloveno" },
  { code: "es", name: "Espanhol" },
  { code: "es_AR", name: "Espanhol (ARG)" },
  { code: "es_ES", name: "Espanhol (ESP)" },
  { code: "es_MX", name: "Espanhol (MEX)" },
  { code: "sw", name: "Suaíli" },
  { code: "sv", name: "Sueco" },
  { code: "ta", name: "Tâmil" },
  { code: "te", name: "Telugu" },
  { code: "th", name: "Tailandês" },
  { code: "tr", name: "Turco" },
  { code: "uk", name: "Ucraniano" },
  { code: "ur", name: "Urdu" },
  { code: "uz", name: "Uzbeque" },
  { code: "vi", name: "Vietnamita" },
  { code: "zu", name: "Zulu" },
];

export const DEFAULT_LANGUAGE = "pt_BR";

export function getLanguageName(code: string): string {
  return META_LANGUAGES.find(l => l.code === code)?.name ?? code;
}
